package fr.soe.a3s.service;

import java.io.IOException;
import java.util.Date;
import java.util.List;

import net.jimmc.jshortcut.JShellLink;
import fr.soe.a3s.dao.CommonDAO;
import fr.soe.a3s.dao.ConfigurationDAO;
import fr.soe.a3s.dao.PreferencesDAO;
import fr.soe.a3s.dao.ProfileDAO;
import fr.soe.a3s.dao.repository.RepositoryDAO;
import fr.soe.a3s.domain.AutoConfig;
import fr.soe.a3s.domain.Profile;
import fr.soe.a3s.domain.configration.FavoriteServer;
import fr.soe.a3s.domain.repository.Repository;
import fr.soe.a3s.exception.LoadingException;
import fr.soe.a3s.exception.WritingException;
import fr.soe.a3s.main.Version;

public class CommonService {

	private static final ConfigurationDAO configurationDAO = new ConfigurationDAO();
	private static final ProfileDAO profileDAO = new ProfileDAO();
	private static final PreferencesDAO preferencesDAO = new PreferencesDAO();
	private static final RepositoryDAO repositoryDAO = new RepositoryDAO();
	private static final CommonDAO commonDAO = new CommonDAO();
	private static String WIKI = "http://www.sonsofexiled.fr/wiki/index.php/1._ArmA3Sync";
	private static String BIS = "http://forums.bistudio.com/showthread.php?162236-ArmA3Sync-launcher-and-addons-synchronization-software-for-ArmA-3&p=2477805#post2477805";
	private static String PayPal = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JS65JS4FUGZWC";

	public void saveAllParameters(int height, int width)
			throws WritingException {

		configurationDAO.getConfiguration().setHeight(height);
		configurationDAO.getConfiguration().setWidth(width);
		configurationDAO.write();
		profileDAO.writeProfiles();
		preferencesDAO.write();
	}

	public void exportAutoConfig(List<String> listSelectedProfileNames,
			List<String> listSelectedFavoriteServerNames,
			List<String> listSelectedRepositoryNames, String path)
			throws WritingException {

		AutoConfig autoConfig = new AutoConfig();

		for (String profileName : listSelectedProfileNames) {
			Profile profile = profileDAO.getMap().get(profileName);
			if (profile != null) {
				profile.setLauncherOptions(null);// clear launcher options
				autoConfig.getProfiles().add(profile);
			}
		}

		List<FavoriteServer> favoriteServers = configurationDAO
				.getConfiguration().getFavoriteServers();

		for (FavoriteServer favoriteServer : favoriteServers) {
			if (listSelectedFavoriteServerNames.contains(favoriteServer
					.getName())) {
				autoConfig.getFavoriteServers().add(favoriteServer);
			}
		}

		for (String repositoryName : listSelectedRepositoryNames) {
			Repository repository = repositoryDAO.getMap().get(repositoryName);
			if (repository != null) {
				Repository clonedRepository = new Repository(
						repository.getName(), repository.getProtocol());
				autoConfig.getRepositories().add(clonedRepository);
			}
		}

		try {
			commonDAO.exportAutoConfig(autoConfig, path);
		} catch (Exception e) {
			e.printStackTrace();
			throw new WritingException();
		}
	}

	public void importAutoConfig(String path) throws LoadingException {

		AutoConfig autoConfig = null;
		try {
			autoConfig = commonDAO.importAutoConfig(path);
			if (autoConfig == null) {
				throw new LoadingException();
			}
		} catch (Exception e) {
			e.printStackTrace();
			throw new LoadingException();
		}

		List<Profile> listProfiles = autoConfig.getProfiles();

		for (Profile profile : listProfiles) {
			profileDAO.getMap().put(profile.getName(), profile);
		}

		List<FavoriteServer> favoriteServers = autoConfig.getFavoriteServers();

		for (FavoriteServer favoriteServer : favoriteServers) {
			configurationDAO.getConfiguration().getFavoriteServers()
					.add(favoriteServer);
		}

		List<Repository> repositories = autoConfig.getRepositories();

		for (Repository repository : repositories) {
			if (!repositoryDAO.getMap().containsKey(repository.getName())) {
				repositoryDAO.getMap().put(repository.getName(), repository);
			}
		}
	}

	public void exportToDesktop(String message, String fileName)
			throws IOException {

		String header = "Generated by ArmA3Sync " + Version.getVersion();
		String date = new Date().toLocaleString();

		String print = header + "\n" + date + "\n\n" + message;

		JShellLink link = new JShellLink();
		String path = JShellLink.getDirectory("desktop") + "/" + fileName;
		commonDAO.writeLog(print, path);
	}

	public int extractBikeys(String sourceDirectoryPath,
			String destinationDirectoryPath) throws IOException {

		return commonDAO.extractBikeys(sourceDirectoryPath,
				destinationDirectoryPath);
	}

	public void cancel() {
		commonDAO.cancel();
	}

	public String getWiki() {
		return WIKI;
	}

	public String getBIS() {
		return BIS;
	}

	public String getPayPal() {
		return PayPal;
	}
}
